//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by WinArk.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDS_TITLE                       129
#define IDR_CONTEXT                     202
#define IDI_CANCEL                      202
#define IDR_BIN1                        204
#define IDI_FILTER                      204
#define IDI_FILTER_ADD                  205
#define IDI_FILTER_DELETE               206
#define IDR_DRIVER                      207
#define IDR_X64_DRIVER                  207
#define IDI_MEMORY                      208
#define IDI_DLL                         209
#define IDD_PROCESS_PROPERTIES          210
#define IDI_NETWORK                     210
#define IDI_OK                          211
#define IDD_ENVVARS                     212
#define IDI_PLAY                        212
#define IDD_TOKEN                       214
#define IDI_REGISTRY                    214
#define IDD_MULTISTRING                 215
#define IDI_STOP                        215
#define IDD_JOB                         216
#define IDI_THREAD                      216
#define IDI_TOOLS                       217
#define IDD_BACKGROUND                  217
#define IDD_STRINGVALUE                 220
#define IDD_NEWKEY                      221
#define IDD_NUMBERVALUE                 222
#define IDD_BINVALUE                    223
#define IDI_WINDOW                      224
#define IDD_EVENTS                      224
#define IDD_EXPORT                      226
#define IDI_PROPERTIES                  228
#define IDI_STACK                       229
#define IDR_BIN2                        231
#define IDI_GEAR                        231
#define IDR_BIN3                        233
#define IDI_FILE                        233
#define IDD_PROGRESS                    234
#define IDI_HANDLE                      234
#define IDD_MODULES1                    235
#define IDI_OBJECT                      235
#define IDD_CONFIG                      236
#define IDD_INLINEHOOKSCAN              237
#define IDI_DISK                        238
#define IDR_PROC_CONTEXT                239
#define IDR_KERNEL_CONTEXT              240
#define IDI_HEAP                        240
#define IDR_ETW_CONTEXT                 241
#define IDI_HEAP2                       241
#define IDI_K                           242
#define IDI_HANDLES                     243
#define IDI_REFRESH                     244
#define IDI_GENERIC                     246
#define IDD_STACK                       247
#define IDI_PROCESS_DELETE              248
#define IDI_PROCESS_NEW                 249
#define IDI_DLL_LOAD                    250
#define IDI_DLL_UNLOAD                  251
#define IDI_THREAD_DELETE               252
#define IDI_THREAD_NEW                  253
#define IDD_FILTERS                     254
#define IDI_U                           254
#define IDD_EVENT_PROPS                 255
#define IDI_DOWN_ARROW                  256
#define IDI_UP_ARROW                    257
#define IDD_FIND                        257
#define IDI_OPEN                        258
#define IDI_FIND                        259
#define IDI_FILTER_EDIT                 260
#define IDI_CANCEL2                     261
#define IDI_OK2                         262
#define IDI_PAUSE                       263
#define IDI_SCROLL                      264
#define IDI_SEARCH                      265
#define IDR_SSDT_CONTEXT                266
#define IDR_SHADOW_SSDT_CONTEXT         267
#define IDR_BIN5                        269
#define IDD_COLORS                      272
#define IDD_GOTOKEY                     274
#define IDD_BYPASS                      275
#define IDI_ICON1                       276
#define IDI_GOTO                        276
#define IDR_POOLTAG                     277
#define IDR_KERNEL_HOOK_CONTEXT         278
#define IDR_SCYLLA_CONTEXT              281
#define IDD_DIALOG1                     282
#define IDD_SCYLLA                      282
#define IDR_DBG_CONTEXT                 286
#define IDR_TASK_CONTEXT                287
#define IDI_FOLDER                      289
#define IDI_TASK_ROOT                   290
#define IDI_TASK                        291
#define IDI_ACTION                      292
#define IDI_TIMER                       293
#define IDB_DONATE                      294
#define IDI_COMPUTER                    295
#define IDI_FOLDER_CLOSED               296
#define IDI_FOLDER_LINK                 297
#define IDI_FOLDER_ACCESSDENIED         298
#define IDI_HIVE                        299
#define IDI_HIVE_ACCESSDENIED           300
#define IDI_FOLDER_UP                   301
#define IDI_BINARY                      302
#define IDI_TEXT                        303
#define IDI_DWORD                       304
#define IDI_ICON3                       305
#define IDI_QWORD                       305
#define IDC_CONFIG_LIST                 1000
#define IDC_VALUE                       1001
#define IDC_APPICON                     1002
#define IDC_HEX                         1002
#define IDC_TREE                        1002
#define IDC_NAME                        1003
#define IDC_SAVE                        1003
#define IDC_BIN                         1004
#define IDC_LOAD                        1004
#define IDC_PARENT                      1005
#define IDC_COLOR                       1005
#define IDC_RESET                       1005
#define IDC_DESC                        1006
#define IDC_STRING                      1006
#define IDC_DEFAULTS                    1006
#define IDC_EXPANDSZ                    1007
#define IDC_EXPAND                      1007
#define IDC_COLLAPSE                    1008
#define IDC_BUTTON1                     1011
#define IDC_PROCESS                     1011
#define IDC_ENV                         1012
#define IDC_THREAD                      1012
#define IDC_ENABLE_DBG_SYS              1012
#define IDC_ENABLE_DBGSYS               1012
#define IDC_TOKEN                       1013
#define IDC_JOB                         1014
#define IDC_CREATED                     1017
#define IDC_UP                          1017
#define IDC_PLATFORM                    1018
#define IDC_DOWN                        1018
#define IDC_COPY                        1019
#define IDC_DELETE                      1019
#define IDC_COPYALL                     1020
#define IDC_NAMES                       1020
#define IDC_LIST                        1021
#define IDC_COMPARE                     1021
#define IDC_USERNAME                    1022
#define IDC_SESSION                     1023
#define IDC_INC_EXC                     1023
#define IDC_INTEGRITY                   1024
#define IDC_ADD                         1024
#define IDC_VIRT                        1025
#define IDC_ELEVATED                    1026
#define IDC_BASIC                       1026
#define IDC_EDIT                        1026
#define IDC_LOGONSESSION                1027
#define IDC_ADVANCED                    1027
#define IDC_GROUP_COUNT                 1028
#define IDC_GROUPS                      1029
#define IDC_USERSID                     1030
#define IDC_PRIVILEGES                  1031
#define IDC_ENABLE                      1033
#define IDC_DISABLE                     1034
#define IDC_CAPS                        1036
#define IDC_PRIV_COUNT                  1037
#define IDC_CAPS_COUNT                  1038
#define IDC_TERM                        1040
#define IDC_PROCLIST                    1041
#define IDC_LIMITS                      1042
#define IDC_BASIC_INFO                  1043
#define IDC_IO                          1044
#define IDC_SILO                        1045
#define IDC_DEC                         1046
#define IDC_BUFFERSIZE                  1046
#define IDC_PID                         1047
#define IDC_EXPORT_REAL                 1047
#define IDC_EXPORTKEY                   1048
#define IDC_KEY                         1049
#define IDC_PATH                        1050
#define IDC_BROWSE                      1051
#define IDC_PROGRESS                    1052
#define IDC_MESSAGE                     1053
#define IDC_INTERCEPT_DRIVER            1054
#define IDC_REMOVE_CALLBACK             1060
#define IDC_SET_CALLBACK                1061
#define IDC_EXPLORE                     1063
#define IDC_COMMANDLINE                 1064
#define IDC_CURDIR                      1065
#define IDC_EXPLORE_DIR                 1066
#define IDC_USER                        1068
#define IDC_STACK                       1069
#define IDC_RESOLVE_SYM                 1070
#define IDC_TEXT                        1072
#define IDC_PROCESSES                   1073
#define IDC_EVENT                       1074
#define IDC_DETAILS                     1075
#define IDC_CASESENSITIVE               1077
#define IDC_FINDNEXT                    1078
#define IDC_WIN_VERSION                 1080
#define IDC_BOOT_TIME                   1081
#define IDC_OPACITY                     1081
#define IDC_USABLE_RAM                  1082
#define IDC_TEXT_COLOR                  1082
#define IDC_PROCESSOR_COUNT             1083
#define IDC_HIT_TEXT_COLOR              1083
#define IDC_PROCESSOR                   1084
#define IDC_LOW_COLOR                   1084
#define IDC_KEY_LIST                    1085
#define IDC_BK_COLOR                    1085
#define IDC_SEL_BK_COLOR                1086
#define IDC_LINE_COLOR                  1087
#define IDC_AUX_COLOR                   1088
#define IDC_TEXT_COLOR8                 1089
#define IDC_CONDBK_COLOR                1089
#define IDC_BYPASS_KDBG                 1094
#define IDC_BYPASS                      1095
#define IDC_BTN_PICKDLL                 1096
#define IDC_GROUP_IMPORTS               1097
#define IDC_TREE_IMPORTS                1098
#define IDC_BTN_SHOW_INVALID            1099
#define IDC_BTN_SHOW_SUSPECT            1100
#define IDC_BTN_CLEAR                   1101
#define IDC_GROUP_IAT_INFO              1102
#define IDC_OEP_ADDRESS                 1103
#define IDC_IAT_ADDRESS                 1104
#define IDC_IAT_SIZE                    1105
#define IDC_BTN_AUTO_SEARCH             1106
#define IDC_BTN_GET_IMPORTS             1107
#define IDC_BTN_AUTO_TRACE              1108
#define IDC_BTN_DUMP                    1109
#define IDC_BTN_PE_REBUILD              1110
#define IDC_BTN_FIX_DUMP                1111
#define IDC_GROUP_LOG                   1112
#define IDC_LIST_LOG                    1113
#define IDC_GROUP_CALLBACK              1114
#define IDC_GROUP_SYSINFO               1115
#define IDC_GROUP_DBGSYS                1116
#define IDC_STATIC_IATSIZE              1117
#define IDC_STATIC_IATADDRESS           1118
#define IDC_STATIC_OEPADDRESS           1119
#define IDC_GROUP_DUMP                  1120
#define IDC_DEBUGGER_LIST               1121
#define IDC_BOOT_MODE                   1122
#define IDC_DISABLE_DRIVER_LOAD         1123
#define IDC_CHECK1                      1124
#define IDC_LOG_HASH                    1124
#define ID_PROCESS_THREADS              32775
#define ID_PROCESS_MODULES              32776
#define ID_PROCESS_KILL                 32777
#define ID_PROCESS_REFRESH              32779
#define ID_PROCESS_PROPERTIES           32780
#define ID_PROCESS_GOTOFILELOCATION     32781
#define ID_PROCESS_DETAILS              32782
#define ID_DETAILS_MODULES              32783
#define ID_DETAILS_THREADS              32784
#define ID_DETAILS_HANDLES              32785
#define ID_PROCESS_HANDLES              32786
#define ID_NEW_MULTIPLESTRINGSVALUE     32786
#define ID_DETAILS_MEMORY               32787
#define ID_PROCESS_MEMORY               32788
#define ID_TREE_NEW                     32789
#define ID_TREE_COPY                    32790
#define ID_TREE_CUT                     32791
#define ID_TREE_PASTE                   32792
#define ID_TREE_DELETE                  32793
#define ID_TREE_COPYKEYNAME             32794
#define ID_TREE_COPYFULLKEYNAME         32795
#define ID_TREE_RENAME                  32796
#define ID_TREE_PERMISSIONS             32797
#define ID_NEW_KEY                      32798
#define ID_NEW_DWORDVALUE               32799
#define ID_NEW_QWORDVALUE               32800
#define ID_NEW_STRINGVALUE              32801
#define ID_NEW_MULTIPLESTRINGVALUE      32802
#define ID_NEW_EXPANDSTRINGVALUE        32803
#define ID_NEW_BINARYVALUE              32804
#define ID_EDIT_RENAME                  32811
#define ID_EDIT_MODIFYVALUE             32812
#define ID_EDIT_PERMISSIONS             32813
#define ID_LIST_NEW                     32814
#define ID_WIN_STATE                    32823
#define ID_WIN_PROPERTIES               32824
#define ID_STATE_SHOW                   32825
#define ID_STATE_HIDE                   32826
#define ID_STATE_HIGHLIGHT              32827
#define ID_STATE_MINIMIZE               32828
#define ID_STATE_MAXMIZE                32829
#define ID_STATE_RESTORE                32830
#define ID_STATE_BRINGTOFRONT           32831
#define ID_STATE_CLOSE                  32832
#define ID_STATE_FLASH                  32833
#define ID_WINDOW_SHOW                  32834
#define ID_WINDOW_HIDE                  32835
#define ID_WINDOW_HIGHLIGHT             32836
#define ID_WINDOW_MINIMIZE              32837
#define ID_WINDOW_MAXMIZE               32838
#define ID_WINDOW_RESTORE               32839
#define ID_WINDOW_BRINGTOFRONT          32840
#define ID_WINDOW_CLOSE                 32841
#define ID_WINDOW_FLASH                 32842
#define ID_WINDOW_PROPERTIES            32843
#define ID_WINDOW_MAXIMIZE              32844
#define ID_WIN_REFRESH                  32845
#define ID_WINDOW_REFRESH               32846
#define ID_FILE_RUNASADMINISTRATOR      32847
#define ID_FILE_EXIT                    32848
#define IDM_EXIT                        32849
#define ID_FILE_RUNASADMIN              32850
#define ID_OPTIONS_ALWAYSONTOP          32851
#define ID_OPTIONS_DARKMODE             32852
#define ID_HELP_ABOUTWINARK             32853
#define ID_LISTEMPTY_PASTE              32854
#define ID_KEY_PROPERTIES               32855
#define ID_REG_CREATEKEY                32856
#define ID_REG_RENAME                   32857
#define ID_REG_COPY                     32858
#define ID_REG_COPYKEYNAME              32859
#define ID_COPY_NAME                    32860
#define ID_REG_COPYFULLKEYNAME          32861
#define ID_COPY_FULLNAME                32862
#define ID_REG_PASTE                    32863
#define ID_REG_REFRES                   32864
#define ID_TREE_REFRESH                 32865
#define ID_REG_DELETE                   32866
#define ID_REG_EXPORT                   32867
#define ID_FILE_EXPORT                  32868
#define ID_REG_IMPORT                   32869
#define ID_FILE_IMPORT                  32870
#define ID_REG_PERMISSIONS              32871
#define ID_KEY_PERMISSIONS              32872
#define ID_LISTDIR_COPY                 32873
#define ID_LISTDIR_DELETE               32874
#define ID_REMOTE_DISCONNECT            32875
#define ID_FILE_DISCONNECT              32876
#define ID_KERNEL_32877                 32877
#define ID_KERNEL_ROUTINES              32878
#define ID_KERNEL_REFRESH               32879
#define ID_NETWORK_REFRESH              32880
#define ID_KERNEL_REMOVE                32881
#define ID_PROCESS_INLINEHOOKSCAN       32882
#define ID_PROC_COPY                    32884
#define ID_THREAD_COPY                  32885
#define ID_PIDDBCACHE_COPY              32886
#define ID_UNLOADEDDRIVERS_COPY         32887
#define ID_THREAD_EXPORT                32888
#define ID_PIDDBCACHE_EXPORT            32889
#define ID_UNLOADEDDRIVERS_EXPORT       32890
#define ID_EVENT_PROPERTIES             32891
#define ID_EVENT_CALLSTACK              32892
#define ID_EVENT_COPY                   32893
#define ID_EVENT_COPYALL                32894
#define ID_MONITOR_START                32895
#define ID_MONITOR_STOP                 32896
#define ID_MONITOR_PAUSE                32897
#define ID_MONITOR_CLEARALL             32898
#define ID_MONITOR_CONFIGUREEVENTS      32899
#define ID_MONITOR_CONFIGUREFILTERS     32900
#define ID_CONFIGURE_FILTERS            32901
#define ID_CONFIGURE_EVENTS             32902
#define ID_VIEW_AUTOSCROLL              32907
#define ID_VIEW_COLUMNS                 32908
#define ID_VIEW_STATUSBAR               32909
#define ID_EDIT_COPYALL                 32911
#define ID_SEARCH_QUICKFIND             32912
#define ID_SEARCH_FINDALL               32913
#define ID_SEARCH_FINDNEXT              32914
#define ID_PIDDBCACHE_REFRESH           32915
#define ID_UNLOADEDDRIVERS_REFRESH      32916
#define ID_SSDT_REFRESH                 32917
#define ID_SSDT_COPY                    32918
#define ID_SSDT_EXPORT                  32919
#define ID_SHADOW_REFRESH               32920
#define ID_SHADOW_COPY                  32921
#define ID_SHADOW_EXPORT                32922
#define ID_KERNEL_REFRESH32923          32923
#define ID_KERNEL_MODULE_REFRESH        32924
#define ID_KERNEL_EXPORT                32925
#define ID_KERNEL_COPY                  32926
#define ID_KERNEL_MODULE_COPY           32927
#define ID_KERNEL_MODULE_EXPORT         32928
#define ID_REG_GOTO                     32929
#define ID_KERNEL_COPY32929             32929
#define ID_KEY_GOTO                     32930
#define ID_NOTIFY_COPY                  32931
#define ID_NOTIFY_EXPORT                32932
#define ID_INLINEHOOK_COPY              32933
#define ID_INLINEHOOK_EXPORT            32934
#define ID_MEMORY_DUMP                  32935
#define ID_OPTIONS_COLORS               32936
#define ID_OPTIONS_FONT                 32937
#define ID_POOLTAG_REFRESH              32938
#define ID_EDIT_FIND32939               32939
#define ID_BIGPOOL_REFRESH              32942
#define ID_KERNEL_ERASE                 32943
#define ID_DPCTIMER_REFRESH             32944
#define ID_IOTIMER_REFRESH              32945
#define ID_MINIFILTER_REFRESH           32946
#define ID_MINIFILTER_CALLBACK          32947
#define ID_SERVICE_START                32948
#define ID_SERVICE_STOP                 32949
#define ID_SERVICE_PAUSE                32950
#define ID_SERVICE_CONTINUE             32951
#define ID_SERVICE_UNINSTALL            32952
#define ID_SERVICE_                     32953
#define ID_SERVICE_PROPERTIES           32954
#define ID_MINIFILTER_REMOVE            32955
#define ID_WFPFILTER_REFRESH            32956
#define ID_WFPFILTER_REMOV              32957
#define ID_WFPFILTER_DELETE             32958
#define ID_RUNAS_SYSTEM                 32959
#define ID_EXIT                         32960
#define ID_PROCESS_EATHOOKSCAN          32961
#define ID_PROCESS_EAT_HOOKSCAN         32962
#define ID_PROCESS_AT_HOOKSCAN          32963
#define ID_ADDRESS_TABLE_HOOKSCAN       32964
#define ID_KERNEL_GOTOFILELOCATION      32965
#define ID_PROCESS_VADINFORMATION       32966
#define ID_PROCESS_VAD_INFO             32967
#define ID_FILE_DUMP                    32968
#define ID_PROCESS_DUMPPROCESS          32969
#define ID_PROCESS_DUMP                 32970
#define ID_KERNEL_DUMP                  32971
#define ID_KERNEL_REMOVEBYNAME          32972
#define ID_KERNEL_REMOVE_BY_NAME        32973
#define ID_KERNEL_EATHOOKSCAN           32974
#define ID_EXTHOST_EXTENSIONTABLE       32975
#define ID_EXTHOST_EXTENSION_TABLE      32976
#define ID_DBG_ADD                      32977
#define ID_DBG_REMOVE                   32978
#define ID_INLINEHOOK_REFRESH           32979
#define ID_INLINEHOOK_COPY32980         32980
#define ID_INLINEHOOK_EXPORT32981       32981
#define ID_KERNEL_INLINEHOOK_REFRESH    32982
#define ID_KERNEL_INLINEHOOK_COPY       32983
#define ID_KERNEL_INLINEHOOK_EXPORT     32984
#define ID_SERVICE_STARTALL             32985
#define ID_SERVICE_START_ALL            32986
#define ID_SERVICE_EXPORTBYPID          32987
#define ID_SERVICE_EXPORT_BY_PID        32988
#define ID_TASK_DISABLE                 32989
#define ID_TASK_RUN                     32990
#define ID_TASK_STOP                    32991
#define ID_TASK_EXPORT                  32992
#define ID_TASK_DELETE                  32993
#define ID_TASK_PROPERTIES              32994
#define ID_TASK_ENABLE                  32995
#define ID_OBJECTCALLBACK_REMOVE        32996
#define ID_OBJECTCALLBACK_ENABLE        32997
#define ID_OBJECTCALLBACK_DISABLE       32998
#define ID_OBJECTCALLBACK_REMOVEBYCOMPANYNAME 32999
#define ID_OBJECTCALLBACK_COPY          33000
#define ID_OBJECTCALLBACK_EXPORT        33001
#define ID_OBJECTCALLBACK_REMOVE_BY_NAME 33002
#define ID_OBJ_CALLBACK_ENABLE          33003
#define ID_OBJ_CALLBACK_DISABLE         33004
#define ID_OBJ_CALLBACK_REMOVE          33005
#define ID_OB_CALLBACK_REMOVE_BY_NAME   33006
#define ID_OB_CALLBACK_REMOVE           33007
#define ID_OB_CALLBACK_DISABLE          33008
#define ID_OB_CALLBACK_ENABLE           33009
#define ID_OB_CALLBACK_COPY             33010
#define ID_OB_CALLBACK_EXPORT           33011
#define ID_OBJECTCALLBACK_REFRESH       33012
#define ID_OB_CALLBACK_REFRESH          33013
#define ID_SERVICE_REFRESH              33014
#define ID_INLINEHOOK_RESTORE           33015
#define ID_INLINEHOOK_REFRESH33016      33016
#define ID_INLINEHOOK_REFRESH_ALL       33017
#define ID_KERNEL_INLINEHOOKSCAN        33018
#define ID_KERNEL_INLINE_HOOK_SCAN      33019
#define ID_PROCESS_RESUME               33020
#define ID_PROCESS_SUS                  33021
#define ID_PROCESS_SUSPEND              33022

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        306
#define _APS_NEXT_COMMAND_VALUE         33023
#define _APS_NEXT_CONTROL_VALUE         1126
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
